name: raneri
description: Modern personel, puantaj ve harcama takip uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Flutter Localizations eklendi
  flutter_localizations:
    sdk: flutter
  
  # Firebase (Güncellendi: Yeni sürümler, Pigeon uyumlu)
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_messaging: ^15.0.4  # Güncellendi
  
  # State Management
  provider: ^6.1.1
  
  # UI
  material_color_utilities: ^0.11.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # PDF
  pdf: ^3.10.7
  printing: ^5.11.0
  path_provider: ^2.1.1
  
  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  
  cupertino_icons: ^1.0.6

  flutter_local_notifications: ^17.0.0

image_picker: ^1.0.4
    # Charts for statistics (opsiyonel)
fl_chart: ^0.66.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # App Icon Değiştirme Paketi (Sadece dev_dependencies'ta olmalı)
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

# App Icon Konfigürasyonu (Tek PNG'nizi kullanacak şekilde ayarlandı)
flutter_launcher_icons:
  android: "launcher_icon"  # Android ikon adı (otomatik oluşur)
  ios: false  # iOS üretimi kapalı
  image_path: "assets/icons/RaneriIcon.png"  # Ana ikon dosyanız (legacy ve foreground için)
  min_sdk_android: 21  # Minimum Android SDK (opsiyonel, ama iyi)
  adaptive_icon_background: "#FFFFFF"  # Adaptive ikon arka planı (beyaz – PNG'nizin şeffaf alanlarını doldurur)
  adaptive_icon_foreground: "assets/icons/RaneriIcon.png"  # Foreground: Aynı PNG'nizi kullanır (şeffaflık korunur)